Use apt to install postfix

diff --git a/packages/postfix/packaging b/packages/postfix/packaging
--- a/packages/postfix/packaging
+++ b/packages/postfix/packaging
@@ -1,26 +1,34 @@
 set -e # exit immediately if a simple command exits with a non-zero status
 set -u # report the usage of uninitialized variables
+# function error() {
+#   echo " !     $*" >&2
+#   exit 1
+# }
 
-# Detect # of CPUs so make jobs can be parallelized
-CPUS=$(grep -c ^processor /proc/cpuinfo)
- # Available variables
-# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
-# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
-export HOME=/var/vcap
-export BDB_PATH=/var/vcap/packages/berkeleydb
-export SASL_PATH=/var/vcap/packages/sasl2
-export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-''} # default to empty
-for package_bin_dir in $(ls -d /var/vcap/packages/*/lib)
-do
-  export LD_LIBRARY_PATH=${package_bin_dir}:$LD_LIBRARY_PATH
-done
+# function topic() {
+#   echo "-----> $*"
+# }
+# APT_OPTIONS="-o debug::nolocking=true"
+# topic "Updating apt caches"
+# apt-get $APT_OPTIONS update
 
-tar xfv postfix/postfix-2.11.9.tar.gz
-cd postfix-2.11.9
-make makefiles CCARGS="-DUSE_SASL_AUTH -DUSE_CYRUS_SASL -I${SASL_PATH}/include/sasl \
-  -DHAS_DB -I${BDB_PATH}/include -DUSE_TLS" \
-  AUXLIBS="-L${BDB_PATH}/lib -ldb -lssl -lcrypto -L${SASL_PATH}/lib -lsasl2"
-make -j${CPUS} && make upgrade \
-  install_root=${BOSH_INSTALL_TARGET} \
-  mail_owner=vcap \
-  setgid_group=admin
+
+# export DEBIAN_FRONTEND="noninteractive"
+# debconf-set-selections <<< "postfix postfix/root_address string root@localhost"
+# debconf-set-selections <<< "postfix postfix/destinations string localhost, localhost.localdomain"
+# debconf-set-selections <<< "postfix postfix/relayhost string example.com"
+# debconf-set-selections <<< "postfix postfix/recipient_delim string +"
+# debconf-set-selections <<< "postfix postfix/mailname string mysmtpserver"
+# debconf-set-selections <<< "postfix postfix/protocols string all"
+# debconf-set-selections <<< "postfix postfix/main_mailer_type select Internet with smarthost"
+# debconf-set-selections <<< "postfix postfix/chattr boolean false"
+# debconf-set-selections <<< "postfix postfix/mynetworks string 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
+# debconf-set-selections <<< "postfix postfix/mailbox_limit string 0"
+# PACKAGES="postfix libsasl2-modules"
+# for PACKAGE in $PACKAGES; do
+#   topic "Fetching .debs for $PACKAGE"
+#   apt-get $APT_OPTIONS -y install $PACKAGE
+# done
+
+#topic "Copying .debs to blobs"
+#cp -a $APT_CACHE_DIR/archives/*.deb $BLOBS_DIR/
